# This is a basic workflow to help you get started with Actions

name: send messages to party

# Controls when the workflow will run
on:
  # push:
  #   branches: [main]
  schedule:
    - cron: '15 3 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run send ${{ secrets.WECOM_BOT_KEY }}
